name: MD <-> PDF Spec Generator

description: Convert markdown files into PDF and generate specification document via GitHub Actions.

inputs:
  accessToken:
    description: Secret GitHub API token
    default: ${{ github.token }}
    required: true
  specDir:
    description: Markdown files directory
    default: "."
    required: true
  outputFilePath:
    description: PDF file directory
    default: "./spec.pdf"
    required: true
  chapterContentsFilename:
    description: chapter contents filename
    default: _contents.md
    required: true
  chapterIndexFilename:
    description: chapter index filename
    default: _index.md
    required: true
  tocSectionStart:
    description: String to identify the start line of toc section
    default: `START toc`
    required: true
  tocSectionEnd:
    description: String to identify the end line of toc section
    default: `END toc`
    required: true
  revisionHistorySectionStart:
    description: String to identify the start line of revision history section
    default: `START revision history`
    required: true
  revisionHistorySectionEnd:
    description: String to identify the end line of revision history section
    default: `END revision history`
    required: true
  revisionCommitRegExp:
    description: Regular expression to identify revision commits 
    default: `^revision(\d+.\d+):.*$`
    required: true

outputs:
  pdfPath:
    description: "File path to generated PDF"

branding:
  icon: file
  color: orange

runs:
  using: "node12"
  main: "dist/index.js"
