on: [push]
name: Spec Generator
jobs:
  generate:
    name: Update TOC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
          npm run build
      - name: Update TOC
        uses: ./.github/actions/update-toc
