name: Spec Generator
on:
    workflow_dispatch:
jobs:
    generatePDF:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - id: generate
              uses: ./
              with:
                  accessToken: ${{ secrets.GITHUB_TOKEN }}
                  specDir: "sample-spec"
                  outputDir: "sample-spec"
                  outputFilename: "spec.pdf"
                  chapterContentsFilename: "_contents.md"
                  chapterIndexFilename: "_index.md"
            - run: echo "${{ steps.generate.outputs.pdfPath }}"
            - uses: actions/upload-artifact@v2
              with:
                  name: spec-pdf
                  path: ${{ steps.generate.outputs.pdfPath }}
