on: [workflow_dispatch]
name: Spec Generator
jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                  npm ci
                  npm run build
            - uses: ./
              with:
                  accessToken: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  workingDir: ${{ './sample-spec' }}
                  outputDir: ${{ './sample-spec' }}
                  outputFilename: ${{ 'spec.pdf' }}
                  sectionContentsFilename: ${{ '_contents' }}
            - uses: actions/upload-artifact@v2
              with:
                  name: spec-pdf
                  path: ./sample-spec/spec.pdf
