name: Spec Generator
on:
    workflow_dispatch:
        inputs:
            specDir:
                description: "Markdown files directory"
                default: "sample-spec"
                required: true
            outputDir:
                description: "PDF file directory"
                default: "./sample-spec"
                required: true
            outputFilename:
                description: "PDF file name"
                default: "spec.pdf"
                required: true
            chapterContentsFilename:
                description: "chapter contents filename"
                default: "_contents.md"
                required: true
            chapterIndexFilename:
                description: "chapter index filename"
                default: "_index.md"
                required: true
    # pull_request:
    #     types: [opened, labeled, synchronize, reopened]
jobs:
    generatePDF:
        #if: ${{ contains(github.event.pull_request.labels.*.names, 'update spec') }}
        runs-on: ubuntu-latest
        steps:
            - run: echo '${{ toJson(github) }}'
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - run: |
                  npm ci
                  npm run build
            - uses: ./
              with:
                  accessToken: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  prNumber: ${{ github.event.pull_request.number }}
                  specDir: ${{ github.event.inputs.specDir }}
                  outputDir: ${{ github.event.inputs.outputDir }}
                  outputFilename: ${{ github.event.inputs.outputFilename }}
                  chapterContentsFilename: ${{ github.event.inputs.chapterContentsFilename }}
                  chapterIndexFilename: ${{ github.event.inputs.chapterIndexFilename }}
            - uses: actions/upload-artifact@v2
              with:
                  name: spec-pdf
                  path: ${{ github.event.inputs.outputDir }}/${{ github.event.inputs.outputFilename }}
