on: [workflow_dispatch]
name: Spec Generator
env:
    SPEC_DIR: ./sample-spec
    OUTPUT_DIR: ./sample-spec
    OUTPUT_FILENAME: spec.pdf
    SECTION_CONTENTS_FILENAME: _contents
jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                  npm ci
                  npm run build
            - uses: ./
              with:
                  accessToken: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  specDir: ${{ env.SPEC_DIR }}
                  outputDir: ${{ env.OUTPUT_DIR }}
                  outputFilename: ${{ env.OUTPUT_FILENAME }}
                  sectionContentsFilename: ${{ env.SECTION_CONTENTS_FILENAME }}
            - uses: actions/upload-artifact@v2
              with:
                  name: spec-pdf
                  path: ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT_FILENAME }}
